# Generated by Django 5.1.4 on 2025-11-23 20:18

import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models
from django.conf import settings
from datetime import timedelta
from django.db import connection


# Data migration functions from original migrations

def update_existing_orders(apps, schema_editor):
    """From 0009: Update existing orders with expires_at and status."""
    Order = apps.get_model('payments', 'Order')
    expiration_minutes = getattr(settings, 'ORDER_EXPIRATION_MINUTES', 15)
    
    for order in Order.objects.all():
        if order.status == 'success':
            order.status = 'successful'
        if not order.expires_at:
            order.expires_at = order.created_at + timedelta(minutes=expiration_minutes)
        order.save()


def reverse_update_existing_orders(apps, schema_editor):
    """Reverse for 0009."""
    Order = apps.get_model('payments', 'Order')
    for order in Order.objects.all():
        if order.status == 'successful':
            order.status = 'success'
        order.expires_at = None
        order.save()


def set_default_payment_scenario(apps, schema_editor):
    """From 0012: Set default payment scenario for devices."""
    Device = apps.get_model('payments', 'Device')
    updated_count = Device.objects.filter(payment_scenario__isnull=True).update(payment_scenario='Yookassa')
    updated_count += Device.objects.filter(payment_scenario='').update(payment_scenario='Yookassa')


def reverse_set_default_payment_scenario(apps, schema_editor):
    """Reverse for 0012."""
    pass


def copy_uuid_to_temp_field(apps, schema_editor):
    """From 0014: Copy UUID values to temporary CharField."""
    Order = apps.get_model('payments', 'Order')
    db_alias = schema_editor.connection.alias
    
    for order in Order.objects.using(db_alias).all():
        order.id_temp = str(order.id)
        order.save(update_fields=['id_temp'])


def check_column_exists(table_name, column_name):
    """Helper function to check if a column exists."""
    with connection.cursor() as cursor:
        vendor = connection.vendor
        
        if vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name=%s AND column_name=%s
            """, [table_name, column_name])
        elif vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info({table_name})")
            columns = [row[1] for row in cursor.fetchall()]
            return column_name in columns
        elif vendor == 'mysql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_schema=DATABASE() AND table_name=%s AND column_name=%s
            """, [table_name, column_name])
        else:
            return False
        
        return cursor.fetchone() is not None


def add_device_status_client_info_fields(apps, schema_editor):
    """From 0018: Add status-specific client info fields to Device."""
    Device = apps.get_model('payments', 'Device')
    db_table = Device._meta.db_table
    
    fields_to_add = [
        ('client_info_pending', models.TextField(blank=True, null=True)),
        ('client_info_paid', models.TextField(blank=True, null=True)),
        ('client_info_not_paid', models.TextField(blank=True, null=True)),
        ('client_info_make_pending', models.TextField(blank=True, null=True)),
        ('client_info_successful', models.TextField(blank=True, null=True)),
    ]
    
    for field_name, field in fields_to_add:
        if not check_column_exists(db_table, field_name):
            field.set_attributes_from_name(field_name)
            with schema_editor.connection.schema_editor() as editor:
                editor.add_field(Device, field)


def reverse_device_status_client_info_fields(apps, schema_editor):
    """Reverse for 0018."""
    Device = apps.get_model('payments', 'Device')
    db_table = Device._meta.db_table
    
    fields_to_remove = [
        ('client_info_pending', models.TextField(blank=True, null=True)),
        ('client_info_paid', models.TextField(blank=True, null=True)),
        ('client_info_not_paid', models.TextField(blank=True, null=True)),
        ('client_info_make_pending', models.TextField(blank=True, null=True)),
        ('client_info_successful', models.TextField(blank=True, null=True)),
    ]
    
    for field_name, field in fields_to_remove:
        if check_column_exists(db_table, field_name):
            field.set_attributes_from_name(field_name)
            with schema_editor.connection.schema_editor() as editor:
                editor.remove_field(Device, field)


def add_make_failed_field(apps, schema_editor):
    """From 0019: Add client_info_make_failed field to Device."""
    Device = apps.get_model('payments', 'Device')
    db_table = Device._meta.db_table
    
    field_name = 'client_info_make_failed'
    field = models.TextField(blank=True, null=True)
    
    if not check_column_exists(db_table, field_name):
        field.set_attributes_from_name(field_name)
        with schema_editor.connection.schema_editor() as editor:
            editor.add_field(Device, field)


def reverse_make_failed_field(apps, schema_editor):
    """Reverse for 0019."""
    Device = apps.get_model('payments', 'Device')
    db_table = Device._meta.db_table
    
    field_name = 'client_info_make_failed'
    field = models.TextField(blank=True, null=True)
    
    if check_column_exists(db_table, field_name):
        field.set_attributes_from_name(field_name)
        with schema_editor.connection.schema_editor() as editor:
            editor.remove_field(Device, field)


def migrate_receipt_order_ids(apps, schema_editor):
    """From 0021: No-op data migration for receipt order IDs."""
    pass


class Migration(migrations.Migration):

    replaces = [('payments', '0001_initial'), ('payments', '0002_remove_device_merchant_id_remove_order_device_uuid_and_more'), ('payments', '0003_device_device_uuid'), ('payments', '0004_alter_device_device_uuid'), ('payments', '0005_device_redirect_url'), ('payments', '0006_tbankpayment_order_external_order_id'), ('payments', '0007_alter_order_status'), ('payments', '0008_remove_order_drink_order_drink_name'), ('payments', '0009_order_expires_at_alter_order_status'), ('payments', '0010_device_payment_scenario'), ('payments', '0011_merchantcredentials'), ('payments', '0012_set_default_payment_scenario'), ('payments', '0013_device_client_info_device_logo_url'), ('payments', '0014_migrate_order_id_to_charfield'), ('payments', '0015_add_client_error_info_to_device'), ('payments', '0016_update_client_error_info_help_text'), ('payments', '0017_order_drink_number'), ('payments', '0018_add_device_status_client_info_fields'), ('payments', '0019_add_make_failed_status'), ('payments', '0020_add_yookassa_receipt_fields'), ('payments', '0021_fix_receipt_order_id_type'), ('payments', '0022_add_test_status_to_device'), ('payments', '0023_add_background_payment_check_fields'), ('payments', '0024_add_client_info_manual_make'), ('payments', '0025_add_background_check_index'), ('payments', '0026_add_status_check_type')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prices', models.JSONField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('bank_account', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateField(default='2024-12-16')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], max_length=50)),
                ('last_interaction', models.DateTimeField()),
                ('merchant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='payments.merchant')),
                ('device_uuid', models.CharField(max_length=255, unique=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('not_paid', 'Not Paid'), ('make_pending', 'Make Pending'), ('successful', 'Successful'), ('failed', 'Failed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.device')),
                ('merchant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.merchant')),
                ('external_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drink_name', models.CharField(default='Unknown', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], max_length=50)),
                ('transaction_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.merchant')),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=50)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.order')),
            ],
        ),
        migrations.CreateModel(
            name='TBankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('payment_id', models.CharField(max_length=20, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(
            code=update_existing_orders,
            reverse_code=reverse_update_existing_orders,
        ),
        migrations.AddField(
            model_name='device',
            name='payment_scenario',
            field=models.CharField(default='Yookassa', help_text='Payment scenario for this device', max_length=50),
        ),
        migrations.CreateModel(
            name='MerchantCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario', models.CharField(max_length=50)),
                ('credentials', models.JSONField(help_text='Credentials in JSON format. Example for Yookassa: {"account_id": "...", "secret_key": "..."}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='payments.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Credentials',
                'verbose_name_plural': 'Merchant Credentials',
                'unique_together': {('merchant', 'scenario')},
            },
        ),
        migrations.RunPython(
            code=set_default_payment_scenario,
            reverse_code=reverse_set_default_payment_scenario,
        ),
        migrations.AddField(
            model_name='device',
            name='client_info',
            field=models.TextField(blank=True, help_text='Custom information displayed to customers on order screen', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to merchant logo image displayed on order screen', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='id_temp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(
            code=copy_uuid_to_temp_field,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_temp',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='external_order_id',
            new_name='payment_reference_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_reference_id',
            field=models.CharField(blank=True, help_text='Payment system reference ID (e.g., Yookassa payment_id)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='client_error_info',
            field=models.TextField(blank=True, help_text='Custom information displayed to customers on error screens. Supports HTML formatting (e.g., <a href="tel:+1234567890">Call support</a>)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='drink_number',
            field=models.CharField(blank=True, help_text='Drink ID at the device (drinkNo from QR code)', max_length=255, null=True),
        ),
        migrations.RunPython(
            code=add_device_status_client_info_fields,
            reverse_code=reverse_device_status_client_info_fields,
        ),
        migrations.RunPython(
            code=add_make_failed_field,
            reverse_code=reverse_make_failed_field,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('not_paid', 'Not Paid'), ('make_pending', 'Make Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('make_failed', 'Make Failed')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prices', models.JSONField()),
                ('available', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, help_text='Receipt metadata in JSON format. Example: {"vat_code": 2, "measure": "piece", "payment_subject": "commodity", "payment_mode": "full_payment"}', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='drink_no',
            field=models.CharField(blank=True, help_text='Drink ID at the device', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Payment amount in kopecks', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_data',
            field=models.JSONField(blank=True, help_text='Complete receipt data sent to Yookassa in JSON format', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='order',
        ),
        migrations.AddField(
            model_name='receipt',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.order'),
        ),
        migrations.RunPython(
            code=migrate_receipt_order_ids,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.order'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('test', 'Test')], max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user was redirected to payment provider (with timezone)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='next_check_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp for next payment status check (with timezone)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_check_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last payment status check (with timezone)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='check_attempts',
            field=models.IntegerField(default=0, help_text='Number of payment status check attempts'),
        ),
        migrations.AddField(
            model_name='order',
            name='failed_presentation_desc',
            field=models.TextField(blank=True, help_text='User-friendly description of failure reason', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('not_paid', 'Not Paid'), ('make_pending', 'Make Pending'), ('manual_make', 'Manual Make'), ('successful', 'Successful'), ('failed', 'Failed'), ('make_failed', 'Make Failed')], max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='client_info_manual_make',
            field=models.TextField(blank=True, help_text='Information displayed to customers when order status is manual_make. Supports HTML formatting.', null=True),
        ),
        migrations.RunSQL(
            sql="\n            CREATE INDEX IF NOT EXISTS payments_order_background_check_idx \n            ON payments_order (status, next_check_at, expires_at) \n            WHERE status = 'pending' AND next_check_at IS NOT NULL;\n            ",
            reverse_sql='DROP INDEX IF EXISTS payments_order_background_check_idx;',
        ),
        migrations.AddField(
            model_name='merchantcredentials',
            name='status_check_type',
            field=models.CharField(choices=[('polling', 'Polling'), ('webhook', 'Webhook'), ('none', 'None')], default='polling', help_text='Type of payment status check: polling (background check), webhook (notification from payment provider), or none (no automatic check)', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status_check_type',
            field=models.CharField(blank=True, choices=[('polling', 'Polling'), ('webhook', 'Webhook'), ('none', 'None')], help_text='Type of payment status check for this order (fixed at creation time)', max_length=20, null=True),
        ),
        migrations.RunSQL(
            sql="UPDATE payments_order SET status_check_type = 'polling' WHERE status_check_type IS NULL;",
            reverse_sql='UPDATE payments_order SET status_check_type = NULL;',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'status_check_type', 'next_check_at'], name='payments_or_status_idx'),
        ),
    ]
