# Generated by Django 5.1.4 on 2024-12-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='device_uuid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drink_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='order_id',
        ),
        migrations.AddField(
            model_name='device',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='payments.merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='valid_until',
            field=models.DateField(default='2024-12-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.drink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.order'),
            preserve_default=False,
        ),
    ]
