# Generated by Django 5.1.4 on 2024-12-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_device_merchant_id_remove_order_device_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_uuid',
            field=models.UUIDField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
