# Generated by Django 5.1.4 on 2024-12-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_device_device_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_uuid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
