# Generated by Django 5.1.4 on 2024-12-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_device_device_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
