# Generated by Django 5.1.4 on 2025-03-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_device_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('payment_id', models.CharField(max_length=20, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='external_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
