# Generated by Django 5.1.4 on 2025-03-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_tbankpayment_order_external_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success')], max_length=50),
        ),
    ]
