# Generated by Django 5.1.4 on 2025-03-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drink',
        ),
        migrations.AddField(
            model_name='order',
            name='drink_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
