# Generated by Django 5.1.4 on 2025-11-12 09:13

from django.db import migrations, models
from django.conf import settings
from datetime import timedelta


def update_existing_orders(apps, schema_editor):
    """
    Data migration to update existing orders:
    1. Update status 'success' to 'successful'
    2. Set expires_at for existing orders as created_at + ORDER_EXPIRATION_MINUTES
    """
    Order = apps.get_model('payments', 'Order')
    
    # Get expiration minutes from settings, default to 15
    expiration_minutes = getattr(settings, 'ORDER_EXPIRATION_MINUTES', 15)
    
    # Update all existing orders
    for order in Order.objects.all():
        # Update status from 'success' to 'successful'
        if order.status == 'success':
            order.status = 'successful'
        
        # Set expires_at if not already set
        if not order.expires_at:
            order.expires_at = order.created_at + timedelta(minutes=expiration_minutes)
        
        order.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse data migration:
    1. Update status 'successful' back to 'success'
    2. Clear expires_at field
    """
    Order = apps.get_model('payments', 'Order')
    
    for order in Order.objects.all():
        # Revert status from 'successful' to 'success'
        if order.status == 'successful':
            order.status = 'success'
        
        # Clear expires_at
        order.expires_at = None
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_order_drink_order_drink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('not_paid', 'Not Paid'), ('make_pending', 'Make Pending'), ('successful', 'Successful'), ('failed', 'Failed')], max_length=50),
        ),
        migrations.RunPython(update_existing_orders, reverse_migration),
    ]
