# Generated by Django 5.1.4 on 2025-11-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_order_expires_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='payment_scenario',
            field=models.CharField(default='Yookassa', help_text='Payment scenario for this device', max_length=50),
        ),
    ]
