# Generated by Django 5.1.4 on 2025-11-12 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_device_payment_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario', models.CharField(max_length=50)),
                ('credentials', models.JSONField(help_text='Credentials in JSON format. Example for Yookassa: {"account_id": "...", "secret_key": "..."}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='payments.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Credentials',
                'verbose_name_plural': 'Merchant Credentials',
                'unique_together': {('merchant', 'scenario')},
            },
        ),
    ]
