# Generated by Django 5.1.4 on 2025-11-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_set_default_payment_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='client_info',
            field=models.TextField(blank=True, help_text='Custom information displayed to customers on order screen', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to merchant logo image displayed on order screen', null=True),
        ),
    ]
