# Generated by Django 5.1.4 on 2025-11-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_migrate_order_id_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='client_error_info',
            field=models.TextField(blank=True, help_text='Custom information displayed to customers on error screens (e.g., support contact)', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_reference_id',
            field=models.CharField(blank=True, help_text='Payment system reference ID (e.g., Yookassa payment_id)', max_length=255, null=True),
        ),
    ]
