# Generated by Django 5.1.4 on 2025-11-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_add_client_error_info_to_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='client_error_info',
            field=models.TextField(blank=True, help_text='Custom information displayed to customers on error screens. Supports HTML formatting (e.g., <a href="tel:+1234567890">Call support</a>)', null=True),
        ),
    ]
