# Generated by Django 5.1.4 on 2025-11-14 13:03

from django.db import migrations, models, connection


def check_column_exists(table_name, column_name):
    """Check if a column exists in the database table."""
    with connection.cursor() as cursor:
        # Get database vendor (postgresql, sqlite, mysql, etc.)
        vendor = connection.vendor
        
        if vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name=%s AND column_name=%s
            """, [table_name, column_name])
        elif vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info({table_name})")
            columns = [row[1] for row in cursor.fetchall()]
            return column_name in columns
        elif vendor == 'mysql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_schema=DATABASE() AND table_name=%s AND column_name=%s
            """, [table_name, column_name])
        else:
            # For other databases, assume column doesn't exist (safe default)
            return False
        
        return cursor.fetchone() is not None


def add_field_if_not_exists(apps, schema_editor):
    """Add fields only if they don't already exist."""
    Device = apps.get_model('payments', 'Device')
    db_table = Device._meta.db_table
    
    fields_to_add = [
        ('client_info_pending', models.TextField(
            blank=True, 
            null=True,
            help_text='Information displayed to customers when order status is pending. Supports HTML formatting.'
        )),
        ('client_info_paid', models.TextField(
            blank=True, 
            null=True,
            help_text='Information displayed to customers when order status is paid. Supports HTML formatting.'
        )),
        ('client_info_not_paid', models.TextField(
            blank=True, 
            null=True,
            help_text='Information displayed to customers when order status is not_paid. Supports HTML formatting.'
        )),
        ('client_info_make_pending', models.TextField(
            blank=True, 
            null=True,
            help_text='Information displayed to customers when order status is make_pending. Supports HTML formatting.'
        )),
        ('client_info_successful', models.TextField(
            blank=True, 
            null=True,
            help_text='Information displayed to customers when order status is successful. Supports HTML formatting.'
        )),
    ]
    
    for field_name, field in fields_to_add:
        if not check_column_exists(db_table, field_name):
            # Field doesn't exist, add it
            field.set_attributes_from_name(field_name)
            with schema_editor.connection.schema_editor() as editor:
                editor.add_field(Device, field)
            print(f"Added field {field_name} to {db_table}")
        else:
            print(f"Field {field_name} already exists in {db_table}, skipping")


def reverse_migration(apps, schema_editor):
    """Remove fields if they exist."""
    Device = apps.get_model('payments', 'Device')
    db_table = Device._meta.db_table
    
    fields_to_remove = [
        ('client_info_pending', models.TextField(blank=True, null=True)),
        ('client_info_paid', models.TextField(blank=True, null=True)),
        ('client_info_not_paid', models.TextField(blank=True, null=True)),
        ('client_info_make_pending', models.TextField(blank=True, null=True)),
        ('client_info_successful', models.TextField(blank=True, null=True)),
    ]
    
    for field_name, field in fields_to_remove:
        if check_column_exists(db_table, field_name):
            field.set_attributes_from_name(field_name)
            with schema_editor.connection.schema_editor() as editor:
                editor.remove_field(Device, field)
            print(f"Removed field {field_name} from {db_table}")
        else:
            print(f"Field {field_name} doesn't exist in {db_table}, skipping removal")


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_order_drink_number'),
    ]

    operations = [
        migrations.RunPython(add_field_if_not_exists, reverse_migration),
    ]
