# Generated by Django 5.1.4 on 2025-11-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_order_drink_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='client_info_make_pending',
            field=models.TextField(blank=True, help_text='Information displayed to customers when order status is make_pending. Supports HTML formatting.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='client_info_not_paid',
            field=models.TextField(blank=True, help_text='Information displayed to customers when order status is not_paid. Supports HTML formatting.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='client_info_paid',
            field=models.TextField(blank=True, help_text='Information displayed to customers when order status is paid. Supports HTML formatting.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='client_info_pending',
            field=models.TextField(blank=True, help_text='Information displayed to customers when order status is pending. Supports HTML formatting.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='client_info_successful',
            field=models.TextField(blank=True, help_text='Information displayed to customers when order status is successful. Supports HTML formatting.', null=True),
        ),
    ]
