# Generated by Django 5.1.4 on 2025-11-24 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial_squashed_0026_add_status_check_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='client_id',
            field=models.CharField(blank=True, help_text='Client ID in TMetr system (UUID format)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional comments about the client', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_interaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='payments.merchant'),
        ),
        migrations.AlterField(
            model_name='device',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Only for Custom scenario. Redirects to this url after successfully created order', null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='valid_until',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.device'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drink_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.merchant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Price in kopecks (no decimal part)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.merchant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order'),
        ),
    ]
