"""
Django settings for coffee_payment project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

BASE_URL = os.getenv('BASE_URL', 'pay.tmetr.ru')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)8hc120s$c)^11n^fl==uogtt9e(qlu^(vc8u%hfy_67to6ox%'

# Tmetr settings
TMETR_TOKEN = os.getenv('TMETR_TOKEN', 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ4VHdiUnlMbnM3WTVkSzV2RlkwQ0xuX0JJNm1GMXU5WkVPQ09SUlRtZkg0In0.eyJleHAiOjE3NjE0NTYyMjYsImlhdCI6MTc2MTQyMDIyOCwiYXV0aF90aW1lIjoxNzYxNDIwMjI2LCJqdGkiOiI0NThlOTE3My1lNTZkLTQyYTItOTcwNy1hYTVjNjNiMzFjYzMiLCJpc3MiOiJodHRwczovL2xvZ2luLmRldi50bWV0ci5ydS9hdXRoL3JlYWxtcy9kZXYtdGVsZW1ldHJ5LXJlYWxtIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImJkYmY1MmQ1LTQ0NzMtNDQ4Yi1hYjA5LTQyYzRlNjIxMWZjZiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImRldi10ZWxlbWV0cnktY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6ImZmZTM1NzllLWQwNDQtNDA3OS04Mjg4LTc0YmM4M2FjMzdiOSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiQklMTElOR19XUklURVIiLCJERVZJQ0VTX1dSSVRFUiIsIlNVQl9DTElFTlRTX0FETUlOIiwiVEVDSE5JQ0FMX0lORk9fQURNSU4iLCJCSUxMSU5HX0FETUlOIiwiVVNFUl9BRE1JTiIsImRlZmF1bHQtcm9sZXMtZGV2LXRlbGVtZXRyeS1yZWFsbSIsIk9XTl9DTElFTlRfUkVBREVSIiwiVVNFUl9SRUFERVIiLCJTVUJfQ0xJRU5UU19SRUFERVIiLCJURUNITklDQUxfSU5GT19XUklURVIiLCJGSU5BTkNFX0lORk9fQURNSU4iLCJPV05fQ0xJRU5UX0FETUlOIiwiU1VCX0NMSUVOVFNfV1JJVEVSIiwiQklMTElOR19SRUFERVIiLCJERVZJQ0VTX1JFQURFUiIsIk9XTl9DTElFTlRfV1JJVEVSIiwib2ZmbGluZV9hY2Nlc3MiLCJURUNITklDQUxfSU5GT19SRUFERVIiLCJVU0VSX1dSSVRFUiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgYXBpIHByb2ZpbGUgcm9sZXMiLCJzaWQiOiJmZmUzNTc5ZS1kMDQ0LTQwNzktODI4OC03NGJjODNhYzM3YjkiLCJsYXN0TmFtZSI6ItCQ0LvQuNC10LIiLCJmaXJzdE5hbWUiOiLQkNGA0YLQtdC8IDEiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiY2xpZW50SWQiOiI1YmUxOGNiYy02Y2JhLTQ3NzQtYjVhYi0xMDQ4MjRjMGZiOGYiLCJnZW5kZXIiOiJNYWxlIiwibmFtZSI6ItCQ0YDRgtC10LwgMSDQkNC70LjQtdCyIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZXhwZXJ0LWNtIiwibG9jYWxlIjoicnUiLCJnaXZlbl9uYW1lIjoi0JDRgNGC0LXQvCAxIiwiZmFtaWx5X25hbWUiOiLQkNC70LjQtdCyIiwiZW1haWwiOiJleHBlcnQtY21AZndzb2Z0LnJ1In0.a7IObblUSdTaREnvcNrAqtEYgNetX--G_rUBK3Hktx3RY0vDEamIceJ2xt55s64BAzVVt1YwuTIEaIUebwcQVtc-npeg3eeEkWObZbGakKxVrBjOCRg4Pkz3RKN7_q8WrvheK3vAjJzb_WCdLXNKhHQSwwW4XWWSp45rYD4f6MvVOOo--DJrQnExs-qaiI0fbMhwxknodixlcUvgZyjxLHzWmtJz4G7vAS3X_ABoTkSPl-0kElqaCtQ77kaRb5S2v6cyWwJEKxBSr9PB-uEztG9hPQ06BTjoUGsA-FmGp_tgWWyNJ8-EuHJOsDX5ndf29STAtq1WwEovZ7WjbtPxlg')
TMETR_HOST = os.getenv('TMETR_HOST', 'test.telemetry.fwsoft.ru')

# Order expiration time in minutes
ORDER_EXPIRATION_MINUTES = 15

# Device online threshold in minutes
# If last heartbeat is older than this value, device is considered offline
DEVICE_ONLINE_THRESHOLD_MINUTES = 15

# Payment scenarios configuration
# Available scenarios:
# - Yookassa: Standard Yookassa payment integration
# - YookassaReceipt: Yookassa with fiscal receipt generation
#   Credentials structure: {
#     "account_id": "...",
#     "secret_key": "...",
#     "is_receipt_mandatory": true/false,
#     "tax_system_code": 1,
#     "timezone": 1,  # optional
#     "vat_code": 2,  # optional fallback
#     "measure": "piece",  # optional fallback
#     "payment_subject": "commodity",  # optional fallback
#     "payment_mode": "full_payment"  # optional fallback
#   }
# - TBank: TBank payment integration
# - Custom: Custom external payment system
PAYMENT_SCENARIOS = ['Yookassa', 'YookassaReceipt', 'TBank', 'Custom']
DEFAULT_PAYMENT_SCENARIO = 'Yookassa'

# Background payment check configuration
PAYMENT_CHECK_INTERVAL_S = 5  # How often to run the background task (seconds)
FAST_TRACK_LIMIT_S = 300  # 5 minutes - threshold for fast vs slow track
FAST_TRACK_INTERVAL_S = 2  # Check every 5 seconds for fast track
SLOW_TRACK_INTERVAL_S = 60  # Check every 60 seconds for slow track
PAYMENT_ATTEMPTS_LIMIT = 50  # Maximum check attempts before marking as failed
PAYMENT_API_TIMEOUT_S = 3  # Timeout for payment provider API calls (seconds)

# Celery configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BEAT_SCHEDULE = {
    'check-pending-payments': {
        'task': 'payments.tasks.check_pending_payments',
        'schedule': PAYMENT_CHECK_INTERVAL_S,
    },
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '2177-147-45-255-118.ngrok-free.app', # Для тестирования
    'pay.tmetr.ru'
]

# Добавьте ваш домен в список доверенных источников CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://2177-147-45-255-118.ngrok-free.app',
    'https://pay.tmetr.ru'
]

# Application definition

INSTALLED_APPS = [
    'payments',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coffee_payment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coffee_payment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use SQLite for testing if DB_NAME is not set
if os.getenv('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Т-Банк API конфигурация
SHOP_ID = '<ShopID>'
SECRET_KEY = '<Secret Key>'
SUCCESS_URL = '<Successful URL>'
FAIL_URL = '<Unsuccessful URL>'
T_BANK_BASE_URL = 'https://securepay.tinkoff.ru'

# Телеметрия API конфигурация
TELEMETRY_API_TOKEN = ''

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            'format': '{"timestamp": "%(asctime)s", "tag": "%(name)s", "level": "%(levelname)s", "message": "%(message)s"}',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'logs/coffee_payment.log',
            'formatter': 'json',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'yookassa_payment_result_webhook': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'yookassa_payment_process': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'show_order_info': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'initiate_payment': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'process_payment_flow': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'payment_status_service': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'check_pending_payments': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}